# Build standalone WizAccountant Android APK (JS embedded; no Metro on phone).
# Bakes EXPO_PUBLIC_API_URL into the bundle. User can still change URL in app Settings.
#
# Usage:
#   .\scripts\build-apk.ps1 -Production
#   .\scripts\build-apk.ps1 -ApiUrl "https://app.ascendbooks.biz"
#   .\scripts\build-apk.ps1 -PcIp 192.168.1.10 -Port 5278
#   .\scripts\build-apk.ps1

param(
  [string]$ApiUrl = "",
  [string]$PcIp = "",
  [int]$Port = 5278,
  [switch]$SkipPrebuild,
  [switch]$Production
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Mobile = Join-Path $Root "mobile\wiz-accountant"

function Set-AndroidSdk {
  if ($env:ANDROID_HOME -and (Test-Path $env:ANDROID_HOME)) { return }
  $sdk = Join-Path $env:LOCALAPPDATA "Android\Sdk"
  if (Test-Path $sdk) {
    $env:ANDROID_HOME = $sdk
    Write-Host "ANDROID_HOME=$env:ANDROID_HOME" -ForegroundColor DarkGray
  }
}

function Set-JavaHome {
  if ($env:JAVA_HOME -and (Test-Path "$env:JAVA_HOME\bin\java.exe")) { return }
  $candidates = @(
    "C:\Program Files\Microsoft\jdk-17.0.19.10-hotspot",
    (Get-ChildItem "$env:ProgramFiles\Microsoft\jdk-*" -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName),
    "$env:ProgramFiles\Android\Android Studio\jbr",
    (Get-ChildItem "$env:ProgramFiles\Java\jdk-*" -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName)
  ) | Where-Object { $_ -and (Test-Path "$_\bin\java.exe") }
  if ($candidates) {
    $env:JAVA_HOME = $candidates[0]
    $env:Path = "$env:JAVA_HOME\bin;$env:Path"
    Write-Host "JAVA_HOME=$env:JAVA_HOME" -ForegroundColor DarkGray
  } else {
    throw "JAVA_HOME not set. Install: winget install Microsoft.OpenJDK.17"
  }
}

function Test-AndroidProjectValid {
  param([string]$Dir)
  (Test-Path (Join-Path $Dir "gradlew.bat")) -and
    (Test-Path (Join-Path $Dir "app\src\main\AndroidManifest.xml"))
}

function Get-LanIp {
  $addrs = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object {
      $_.IPAddress -notlike '127.*' -and
      $_.IPAddress -notlike '169.254*' -and
      $_.PrefixOrigin -ne 'WellKnown'
    }
  foreach ($a in $addrs) {
    $adapter = Get-NetAdapter -InterfaceIndex $a.InterfaceIndex -ErrorAction SilentlyContinue
    if (-not $adapter) { continue }
    if ($adapter.Name -match 'vEthernet|Virtual|VPN|WSL|Hyper-V|Docker') { continue }
    if ($adapter.Name -match 'Wi-?Fi|WLAN|Ethernet') { return $a.IPAddress }
  }
  $home = $addrs | Where-Object { $_.IPAddress -match '^(192\.168|10\.)\d+\.\d+$' } |
    Select-Object -First 1 -ExpandProperty IPAddress
  if ($home) { return $home }
  return ($addrs | Select-Object -First 1 -ExpandProperty IPAddress)
}

function Resolve-ApiUrl {
  param([string]$Url, [string]$Ip, [int]$ApiPort)
  if ($Url) {
    if ($Url -notmatch '^https?://') { $Url = "http://$Url" }
    if ($Url -notmatch ':\d+(/|$)' -and $Url -notmatch '^https://') { $Url = "$Url`:$ApiPort" }
    return $Url.TrimEnd('/')
  }
  if ($Ip) { return "http://$($Ip.Trim()):$ApiPort" }
  $lan = Get-LanIp
  if ($lan) {
    Write-Host "Auto-detected PC IP: $lan" -ForegroundColor Cyan
    return "http://${lan}:$ApiPort"
  }
  Write-Host "Using emulator default 10.0.2.2:$ApiPort (pass -PcIp for physical phone)" -ForegroundColor Yellow
  return "http://10.0.2.2:$ApiPort"
}

function Set-BuildApiEnv {
  param([string]$MobileRoot, [string]$Url)
  $env:EXPO_PUBLIC_API_URL = $Url
  $env:NODE_ENV = "production"
  $envFile = Join-Path $MobileRoot ".env.production.local"
  @(
    "# Generated by scripts/build-apk.ps1"
    "EXPO_PUBLIC_API_URL=$Url"
  ) | Set-Content -Path $envFile -Encoding utf8
  Write-Host "API URL for this build: $Url" -ForegroundColor Cyan
}

function Enable-AndroidCleartextHttp {
  param([string]$AndroidDir)
  $resXml = Join-Path $AndroidDir "app\src\main\res\xml"
  if (-not (Test-Path $resXml)) { New-Item -ItemType Directory -Path $resXml -Force | Out-Null }
  @"
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
"@ | Set-Content -Path (Join-Path $resXml "network_security_config.xml") -Encoding utf8
  $manifest = Join-Path $AndroidDir "app\src\main\AndroidManifest.xml"
  if (-not (Test-Path $manifest)) { return }
  $c = Get-Content $manifest -Raw
  if ($c -notmatch 'usesCleartextTraffic') {
    $c = $c -replace '<application ', '<application android:usesCleartextTraffic="true" '
  }
  if ($c -notmatch 'networkSecurityConfig') {
    $c = $c -replace '<application ', '<application android:networkSecurityConfig="@xml/network_security_config" '
  }
  Set-Content -Path $manifest -Value $c.TrimEnd() -NoNewline
}

function Enable-LocalReleaseSigning {
  param([string]$AndroidDir)
  $appGradle = Join-Path $AndroidDir "app\build.gradle"
  if (-not (Test-Path $appGradle)) { return }
  $c = Get-Content $appGradle -Raw
  if ($c -match 'release\s*\{' -and $c -notmatch 'signingConfig signingConfigs\.debug') {
    $c = $c -replace '(release\s*\{)', "`$1`n            signingConfig signingConfigs.debug"
    Write-Host "Release APK signed with debug keystore (local install)" -ForegroundColor DarkGray
  }
  Set-Content -Path $appGradle -Value $c.TrimEnd() -NoNewline
}

if (-not (Test-Path $Mobile)) { throw "Mobile app not found: $Mobile" }

if ($Production) {
  $ApiUrl = "https://app.ascendbooks.biz"
  Write-Host "Production build -> $ApiUrl" -ForegroundColor Cyan
} else {
  $ApiUrl = Resolve-ApiUrl -Url $ApiUrl -Ip $PcIp -ApiPort $Port
  Write-Host "(LAN build: phone + PC on same Wi-Fi; API on port $Port)" -ForegroundColor DarkGray
}
Set-BuildApiEnv -MobileRoot $Mobile -Url $ApiUrl

Set-JavaHome
Set-AndroidSdk

$androidDir = Join-Path $Mobile "android"
if (-not $SkipPrebuild -or -not (Test-AndroidProjectValid $androidDir)) {
  Push-Location $Mobile
  try {
    Write-Host "npm install..." -ForegroundColor Cyan
    npm install
    if (-not (Test-AndroidProjectValid $androidDir)) {
      Write-Host "expo prebuild --platform android --clean..." -ForegroundColor Cyan
      Set-BuildApiEnv -MobileRoot $Mobile -Url $ApiUrl
      npx.cmd expo prebuild --platform android --clean
      if ($LASTEXITCODE -ne 0) { throw "expo prebuild failed" }
    }
  } finally { Pop-Location }
}

if (-not (Test-AndroidProjectValid $androidDir)) { throw "android/ missing. Install Android Studio SDK or re-run prebuild." }

Enable-AndroidCleartextHttp $androidDir
Enable-LocalReleaseSigning $androidDir

$gradleProps = Join-Path $androidDir "gradle.properties"
if (Test-Path $gradleProps) {
  $p = Get-Content $gradleProps -Raw
  $p = $p -replace 'reactNativeArchitectures=.*', 'reactNativeArchitectures=arm64-v8a'
  Set-Content -Path $gradleProps -Value $p.TrimEnd()
}

Write-Host "Gradle assembleRelease..." -ForegroundColor Cyan
Push-Location $androidDir
try {
  Set-BuildApiEnv -MobileRoot $Mobile -Url $ApiUrl
  & .\gradlew.bat clean assembleRelease
  if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
} finally { Pop-Location }

$apk = Join-Path $androidDir "app\build\outputs\apk\release\app-release.apk"
if (-not (Test-Path $apk)) { throw "APK not found: $apk" }

$dest = if ($Production) {
  Join-Path $Root "WizAccountant-production.apk"
} else {
  Join-Path $Root "WizAccountant-lite.apk"
}
Copy-Item $apk $dest -Force
$sizeMb = [math]::Round((Get-Item $dest).Length / 1MB, 2)

Write-Host ""
Write-Host "SUCCESS" -ForegroundColor Green
Write-Host "  APK: $dest ($sizeMb MB)" -ForegroundColor Green
Write-Host "  API baked in: $ApiUrl" -ForegroundColor Green
Write-Host ""
Write-Host "Install: copy APK to phone, allow unknown sources, open file." -ForegroundColor Cyan
if ($Production) {
  Write-Host "  Login: approver@pilot.local / pilot (or preparer@pilot.local)" -ForegroundColor Cyan
  Write-Host "  Pair connector to https://app.ascendbooks.biz" -ForegroundColor Cyan
} else {
  Write-Host "  Run API on PC; connector must be online for Sage reads." -ForegroundColor Cyan
}
